# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish new npm version

on:
  workflow_dispatch

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          registry-url: https://registry.npmjs.org/
      - run: npm install -g @angular/cli@14.2.12
      - run: npm install
      - run: ng build "angular-sdk"
      - run: |
          cd dist/angular-sdk
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
